#!/usr/bin/env python3
"""
FTP/SFTP Server Setup Script
Configures vsftpd and SSH for secure file transfers
"""

import os
import sys
import json
import subprocess
import shutil
from pathlib import Path
from typing import Dict, Any, Optional


class FTPServerSetup:
    """Handles FTP/SFTP server installation and configuration."""
    
    def __init__(self, config_file: str = "settings.json"):
        self.config = self._load_config(config_file)
        self.ftp_config = self.config.get('ftp_config', {})
        self.security = self.config.get('security', {})
    
    def _load_config(self, config_file: str) -> Dict[str, Any]:
        """Load configuration from JSON file."""
        config_path = Path(config_file)
        
        if not config_path.exists():
            print(f"✗ Configuration file not found: {config_file}")
            sys.exit(1)
        
        try:
            with open(config_path, 'r') as f:
                return json.load(f)
        except json.JSONDecodeError as e:
            print(f"✗ Invalid JSON in configuration file: {e}")
            sys.exit(1)
    
    def check_root(self) -> bool:
        """Check if script is run as root."""
        if os.geteuid() != 0:
            print("✗ This script must be run as root")
            return False
        return True
    
    def install_packages(self) -> bool:
        """Install required packages."""
        print("\n📦 Installing required packages...")
        
        packages = ['vsftpd', 'openssh-server']
        
        if self.security.get('fail2ban_enabled', False):
            packages.append('fail2ban')
        
        try:
            subprocess.run(
                ['apt', 'update'],
                check=True,
                capture_output=True
            )
            
            subprocess.run(
                ['apt', 'install', '-y'] + packages,
                check=True,
                capture_output=True
            )
            
            print("✓ Packages installed successfully")
            return True
            
        except subprocess.CalledProcessError as e:
            print(f"✗ Failed to install packages: {e}")
            return False
    
    def create_ftp_group(self) -> bool:
        """Create FTP users group."""
        print("\n👥 Creating FTP users group...")
        
        group_name = self.ftp_config.get('ftp_group', 'ftpusers')
        
        try:
            subprocess.run(
                ['groupadd', '-f', group_name],
                check=True,
                capture_output=True
            )
            print(f"✓ Group '{group_name}' created")
            return True
            
        except subprocess.CalledProcessError as e:
            print(f"✗ Failed to create group: {e}")
            return False
    
    def configure_vsftpd(self) -> bool:
        """Configure vsftpd server."""
        print("\n⚙️  Configuring vsftpd...")
        
        config_file = Path('/etc/vsftpd.conf')
        backup_file = Path('/etc/vsftpd.conf.backup')
        
        # Backup existing config
        if config_file.exists() and not backup_file.exists():
            shutil.copy(config_file, backup_file)
            print(f"✓ Backed up existing config to {backup_file}")
        
        config_content = f"""# vsftpd configuration
# Generated by FTP Setup Script

# Basic settings
listen=YES
listen_ipv6=NO
anonymous_enable=NO
local_enable=YES
write_enable=YES
local_umask=022
dirmessage_enable=YES
use_localtime=YES
xferlog_enable=YES
connect_from_port_20=YES

# Security settings
chroot_local_user=YES
allow_writeable_chroot={'YES' if self.ftp_config.get('writeable_chroot', True) else 'NO'}
secure_chroot_dir=/var/run/vsftpd/empty
pam_service_name=vsftpd

# User restrictions
userlist_enable=YES
userlist_file={self.ftp_config.get('allowed_users_file', '/etc/vsftpd.userlist')}
userlist_deny=NO

# Passive mode configuration
pasv_enable=YES
pasv_min_port={self.ftp_config.get('passive_port_min', 40000)}
pasv_max_port={self.ftp_config.get('passive_port_max', 40100)}

# Performance settings
max_clients={self.ftp_config.get('max_clients', 50)}
max_per_ip={self.ftp_config.get('max_per_ip', 5)}

# Logging
xferlog_std_format=NO
log_ftp_protocol=YES
syslog_enable=YES

# Timeouts
idle_session_timeout=600
data_connection_timeout=120

# File operations
file_open_mode=0666
local_umask=022
"""
        
        try:
            with open(config_file, 'w') as f:
                f.write(config_content)
            
            print("✓ vsftpd configuration written")
            return True
            
        except IOError as e:
            print(f"✗ Failed to write vsftpd config: {e}")
            return False
    
    def configure_ssh(self) -> bool:
        """Configure SSH for SFTP."""
        print("\n🔐 Configuring SSH for SFTP...")
        
        sshd_config = Path('/etc/ssh/sshd_config')
        
        # Check if SFTP subsystem is enabled
        try:
            with open(sshd_config, 'r') as f:
                content = f.read()
            
            if 'Subsystem sftp' not in content:
                with open(sshd_config, 'a') as f:
                    f.write('\n# SFTP Subsystem\n')
                    f.write('Subsystem sftp /usr/lib/openssh/sftp-server\n')
                
                print("✓ SFTP subsystem enabled")
            else:
                print("✓ SFTP subsystem already enabled")
            
            return True
            
        except IOError as e:
            print(f"✗ Failed to configure SSH: {e}")
            return False
    
    def setup_firewall(self) -> bool:
        """Configure firewall rules."""
        print("\n🔥 Configuring firewall...")
        
        try:
            # Check if UFW is installed
            subprocess.run(
                ['which', 'ufw'],
                check=True,
                capture_output=True
            )
            
            # Allow FTP ports
            ports = [
                ('20/tcp', 'FTP data'),
                ('21/tcp', 'FTP control'),
                ('22/tcp', 'SSH/SFTP'),
                (f"{self.ftp_config.get('passive_port_min', 40000)}:{self.ftp_config.get('passive_port_max', 40100)}/tcp", 'FTP passive')
            ]
            
            for port, description in ports:
                subprocess.run(
                    ['ufw', 'allow', port],
                    capture_output=True
                )
                print(f"✓ Allowed {description}: {port}")
            
            subprocess.run(['ufw', 'reload'], capture_output=True)
            
            return True
            
        except subprocess.CalledProcessError:
            print("⚠ UFW not installed, skipping firewall configuration")
            return True
    
    def setup_fail2ban(self) -> bool:
        """Configure fail2ban for FTP."""
        if not self.security.get('fail2ban_enabled', False):
            print("\n⚠ fail2ban disabled in config, skipping")
            return True
        
        print("\n🛡️  Configuring fail2ban...")
        
        jail_config = f"""[vsftpd]
enabled = true
port = ftp,ftp-data,ftps,ftps-data
logpath = /var/log/vsftpd.log
maxretry = {self.security.get('max_login_fails', 3)}
bantime = {self.security.get('ban_time_minutes', 60) * 60}
findtime = 600

[sshd]
enabled = true
port = ssh
logpath = /var/log/auth.log
maxretry = {self.security.get('max_login_fails', 3)}
bantime = {self.security.get('ban_time_minutes', 60) * 60}
"""
        
        try:
            with open('/etc/fail2ban/jail.local', 'w') as f:
                f.write(jail_config)
            
            subprocess.run(
                ['systemctl', 'restart', 'fail2ban'],
                check=True,
                capture_output=True
            )
            
            print("✓ fail2ban configured and started")
            return True
            
        except (IOError, subprocess.CalledProcessError) as e:
            print(f"✗ Failed to configure fail2ban: {e}")
            return False
    
    def create_ftp_root(self) -> bool:
        """Create FTP root directory."""
        print("\n📁 Creating FTP root directory...")
        
        ftp_root = Path(self.ftp_config.get('ftp_root', '/srv/ftp'))
        
        try:
            ftp_root.mkdir(parents=True, exist_ok=True)
            os.chown(ftp_root, 0, 0)  # root:root
            os.chmod(ftp_root, 0o755)
            
            print(f"✓ FTP root created at {ftp_root}")
            return True
            
        except OSError as e:
            print(f"✗ Failed to create FTP root: {e}")
            return False
    
    def start_services(self) -> bool:
        """Start and enable FTP services."""
        print("\n🚀 Starting services...")
        
        services = ['vsftpd', 'ssh']
        
        for service in services:
            try:
                subprocess.run(
                    ['systemctl', 'enable', service],
                    check=True,
                    capture_output=True
                )
                subprocess.run(
                    ['systemctl', 'restart', service],
                    check=True,
                    capture_output=True
                )
                print(f"✓ {service} enabled and started")
                
            except subprocess.CalledProcessError as e:
                print(f"✗ Failed to start {service}: {e}")
                return False
        
        return True
    
    def verify_setup(self) -> bool:
        """Verify the setup is working."""
        print("\n✅ Verifying setup...")
        
        checks = [
            ('vsftpd', 'vsftpd service'),
            ('ssh', 'SSH service'),
        ]
        
        all_ok = True
        
        for service, description in checks:
            try:
                result = subprocess.run(
                    ['systemctl', 'is-active', service],
                    capture_output=True,
                    text=True
                )
                
                if result.stdout.strip() == 'active':
                    print(f"✓ {description} is running")
                else:
                    print(f"✗ {description} is not running")
                    all_ok = False
                    
            except subprocess.CalledProcessError:
                print(f"✗ Could not check {description}")
                all_ok = False
        
        return all_ok
    
    def run(self) -> bool:
        """Run the complete setup process."""
        print("=" * 80)
        print("FTP/SFTP SERVER SETUP".center(80))
        print("=" * 80)
        
        if not self.check_root():
            return False
        
        steps = [
            ("Installing packages", self.install_packages),
            ("Creating FTP group", self.create_ftp_group),
            ("Creating FTP root", self.create_ftp_root),
            ("Configuring vsftpd", self.configure_vsftpd),
            ("Configuring SSH", self.configure_ssh),
            ("Setting up firewall", self.setup_firewall),
            ("Setting up fail2ban", self.setup_fail2ban),
            ("Starting services", self.start_services),
            ("Verifying setup", self.verify_setup),
        ]
        
        for description, func in steps:
            if not func():
                print(f"\n✗ Setup failed at: {description}")
                return False
        
        self._print_summary()
        return True
    
    def _print_summary(self):
        """Print setup summary."""
        print("\n" + "=" * 80)
        print("SETUP COMPLETE".center(80))
        print("=" * 80)
        print("\n📊 Server Information:")
        print(f"   FTP Root: {self.ftp_config.get('ftp_root', '/srv/ftp')}")
        print(f"   Allowed Users File: {self.ftp_config.get('allowed_users_file', '/etc/vsftpd.userlist')}")
        print(f"   FTP Group: {self.ftp_config.get('ftp_group', 'ftpusers')}")
        
        print(f"\n🔒 Security:")
        print(f"   fail2ban: {'Enabled' if self.security.get('fail2ban_enabled') else 'Disabled'}")
        print(f"   Max login fails: {self.security.get('max_login_fails', 3)}")
        
        print(f"\n📝 Next Steps:")
        print(f"   1. Run ./ftp_user_manager.py to create FTP users")
        print(f"   2. Users will be created in {self.ftp_config.get('ftp_root', '/srv/ftp')}")
        print(f"   3. Credentials will be saved to {self.config.get('logging', {}).get('credentials_file', '/root/.ftp_credentials.csv')}")
        print("\n" + "=" * 80 + "\n")


def main():
    """Main execution function."""
    config_file = sys.argv[1] if len(sys.argv) > 1 else "settings.json"
    
    setup = FTPServerSetup(config_file)
    success = setup.run()
    
    sys.exit(0 if success else 1)


if __name__ == '__main__':
    main()
